driver=com.mysql.cj.jdbc.Driver
url=jdbc\:mysql\://localhost\:3306/usersdb
username=root
password=Mansi@12
addmsg=Data Saved Succesfully\!\n
updatemsg=Data updated succesfully\!\n
deletemsg=Data deleted succesfully\!\n
